"""Configuration loading utilities.

Supports loading experiment configurations from:
- JSON files (generated by Python config scripts)
- TOML files (alternative format)
"""

import json
import tomllib
from pathlib import Path
from typing import Any, Dict, Optional


def load_json_config(filepath: str) -> Dict[str, Any]:
    """Load a JSON configuration file."""
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def load_toml_config(filepath: str, case_index: int) -> Optional[Dict[str, Any]]:
    """Load a test case from a TOML configuration file by index.

    Args:
        filepath: Path to the TOML file.
        case_index: The 'index' field to search for in test_cases list.

    Returns:
        The matching test case dict, or None if not found.
    """
    with open(filepath, "rb") as f:
        data = tomllib.load(f)

    for case in data.get("test_cases", []):
        if case.get("index") == case_index:
            # Normalize 'layers' key: list -> dict with 1-based integer keys
            if "layers" in case:
                case["layers"] = {i + 1: k for i, k in enumerate(case["layers"])}
            return case
    return None
